name: Verilator-CI
on: [push]
jobs:
  linux:
    name: Test Verilator
    runs-on: ubuntu-24.04
    steps:
      - run: |
             sudo apt-get update
             sudo apt-get install -y verilator
             uname -a
             lsb_release -a
             verilator -version
