name: Verilator-CI
on: [push]
jobs:
  linux:
    name: Test Verilator
    runs-on: ubuntu-24.04
    strategy:
        matrix:
          include:
            - compiler: ghc-9.8.2
              compilerKind: ghc
              compilerVersion: 9.8.2
              setup-method: ghcup
              allow-failure: false
            - compiler: ghc-9.4.8
              compilerKind: ghc
              compilerVersion: 9.4.8
              setup-method: ghcup
              allow-failure: false
        fail-fast: false
    steps:
      - run: |
             mkdir -p "$HOME/.ghcup/bin"
             curl -sL https://downloads.haskell.org/ghcup/0.1.20.0/x86_64-linux-ghcup-0.1.20.0 > "$HOME/.ghcup/bin/ghcup"
             sudo chmod a+x "$HOME/.ghcup/bin/ghcup"
             "$HOME/.ghcup/bin/ghcup" install ghc ${{ matrix.compilerVersion }} || (cat "$HOME"/.ghcup/logs/*.* && false)
             "$HOME/.ghcup/bin/ghcup" install cabal 3.10.2.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
             sudo apt-get update
             sudo apt-get install -y verilator
             uname -a
             lsb_release -a
             verilator -version
             ghc --version
             git clone https://github.com/satnam6502/xilinx-lava.git
             cd xilinx-lava
             cabal test
             verilator +1800-2017ext+sv verilator.vlt --binary --trace -Wall -cc --build --clk clk --top-module nandgate_sim nandgate.sv nandgate_sim.sv
             obj_dir/Vnandgate_sim +trace


    
