name: Verilator-CI
on: [push]

defaults:
    run:
      shell: bash

jobs:
  linux:
    name: Test Verilator
    runs-on: ubuntu-24.04
    strategy:
        matrix:
          include:
            - compiler: ghc-9.8.2
              compilerKind: ghc
              compilerVersion: 9.8.2
              setup-method: ghcup
              allow-failure: false
            - compiler: ghc-9.4.8
              compilerKind: ghc
              compilerVersion: 9.4.8
              setup-method: ghcup
              allow-failure: false
        fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: source
      - run: |
          cd source
          ls
          g++ hello.cpp
          ./a.out
      - name: restore ghc
        uses: actions/cache/restore@v4
        with:
               key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
               path: ~/.ghcup/bin
               restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-
      - run: |
             export GHCUP_INSTALL_BASE_PREFIX=$HOME
             export PATH=$HOME/.ghcup/bin:$PATH
             mkdir -p "$HOME/.ghcup/bin"
             sudo chmod a+x "$HOME/.ghcup/bin/ghcup"
             ghcup install ghc ${{ matrix.compilerVersion }}
             ghcup set ghc ${{ matrix.compilerVersion }}
             ghcup install cabal 3.10.3.0
             sudo apt-get update
             sudo apt-get install -y verilator
             uname -a
             lsb_release -a
             verilator -version
             which ghc
             ghc --version
             git clone https://github.com/satnam6502/xilinx-lava.git
             cd xilinx-lava
      - name: save ghc
        uses: actions/cache/save@v4
        if: always()
        with:
               key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
               path: ~/.ghcup/bin         
      - name: restore cabal cache
        uses: actions/cache/restore@v4
        with:
                key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
                path: ~/.cabal/store
                restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-
      - run: |
             pwd
             echo $HOME
             cabal v2-update
             cd xilinx-lava
             cabal v2-test
             verilator +1800-2017ext+sv verilator.vlt --binary --trace -Wall --top-module nandgate_sim nandgate.sv nandgate_sim.sv
             ls -l obj_dir/Vnandgate_sim
             # obj_dir/Vnandgate_sim +trace
             cp $GITHUB_WORKSPACE/source/hello.cpp .
             g++ hello.cpp
             file a.out
             ./a.out
             cd obj_dir
             file Vnandgate_sim
             ./Vnandgate_sim --help
             ./Vnandgate_sim +trace
      - name: save cabal cache
        uses: actions/cache/save@v4
        if: always()
        with:
               key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
               path: ~/.cabal/store

    
